<?php

namespace QueryBuilder\Grammars;

use QueryBuilder\Grammar;

/**
 * Class OracleGrammar
 *
 * @author Juan Gamonal H <juangamonalh@gmail.com>
 * @package QueryBuilder\Grammars
 */
class OracleGrammar extends Grammar
{
    public function limit(int $limit): string
    {
        return parent::limit($limit); // TODO: Change the autogenerated stub
    }
}
